// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiBFlqjj7c0w98lRz_pvSkAVFp9hfcJ34',
    appId: '1:305192070393:web:c4decbc5641da85a104628',
    messagingSenderId: '305192070393',
    projectId: 'cautious-waffle-crud',
    authDomain: 'cautious-waffle-crud.firebaseapp.com',
    storageBucket: 'cautious-waffle-crud.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcLMflBQzuQ_Y-WZPH1DrxZn37smpRznw',
    appId: '1:305192070393:android:0cc44d957acb7297104628',
    messagingSenderId: '305192070393',
    projectId: 'cautious-waffle-crud',
    storageBucket: 'cautious-waffle-crud.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9t7f6dbFa9oUMbv3hiwe7SM14qPc6n4Q',
    appId: '1:305192070393:ios:1864e0b7d4226b08104628',
    messagingSenderId: '305192070393',
    projectId: 'cautious-waffle-crud',
    storageBucket: 'cautious-waffle-crud.appspot.com',
    iosClientId: '305192070393-etiba3tgou3h8s9pntjk2c45rj5b0f10.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudFiesta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9t7f6dbFa9oUMbv3hiwe7SM14qPc6n4Q',
    appId: '1:305192070393:ios:1864e0b7d4226b08104628',
    messagingSenderId: '305192070393',
    projectId: 'cautious-waffle-crud',
    storageBucket: 'cautious-waffle-crud.appspot.com',
    iosClientId: '305192070393-etiba3tgou3h8s9pntjk2c45rj5b0f10.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudFiesta',
  );
}
